# Generated by Django 4.2.1 on 2023-05-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_name', models.CharField(max_length=255)),
                ('parking_tot_cars', models.BigIntegerField(blank=True, default=0)),
                ('parking_created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_idnum', models.CharField(default='000000', max_length=6)),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_is_parked', models.BooleanField(default=False)),
                ('car_parked_at', models.DateTimeField(auto_now_add=True)),
                ('car_updated_at', models.DateTimeField(auto_now=True)),
                ('car_parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.parking')),
            ],
        ),
    ]
